---
- name: add certbot deb repository
  apt_repository: repo='deb http://httpredir.debian.org/debian {{ debian.version }}-backports main' state=present

- name: install certbot package
  apt: name={{ item }} state=latest default_release={{ debian.version }}-backports update_cache=yes
  with_items:
    - certbot

- name: get certbot path
  command: "which certbot"
  register: certbot_path

- name: install certbot renew daily task
  cron: name="certbot renew" hour="8" job="{{ item }} -q renew --pre-hook "service nginx stop" --post-hook "service nginx start""
  with_items: '{{ certbot_path.stdout }}'
