---
- name: add certbot deb repository
  apt_repository: repo='deb http://httpredir.debian.org/debian {{ debian.version }}-backports main' state=present

- name: install certbot package
  apt:
    name: {{ packages }}
    state: latest
    default_release: {{ debian.version }}-backports
    update_cache: yes
    force: yes
  vars:
    packages:
      - certbot

- name: get certbot path
  command: "which certbot"
  register: certbot_path

- name: install certbot renew daily task
  cron: name="certbot daily renew" hour="7" minute="0" job='{{ item }} -q renew --pre-hook "service nginx stop" --post-hook "service nginx start"'
  with_items: '{{ certbot_path.stdout }}'
