---
- name: add certbot deb repository
  apt_repository: repo='deb http://httpredir.debian.org/debian {{ debian.version }}-backports main' state=present

- name: install certbot package
  apt: name={{ item }} state=latest default_release={{ debian.version }}-backports update_cache=yes
  with_items:
    - certbot

- name: install certbot renew daily task
  cron: name="certbot renew" hour="8" job="certbot renew --quiet"
